### ISSUE TITLE
Exception while calling proto_flow() on target dc.lab.local: zip() argument 2 is longer than argument 1

### ISSUE THREAD

**Issue by w3soul** [Pennyw0rth/NetExec#613]
Works fine for all Domain Computers, however for Domain Controller, after "Pwn3d!" throws strange error:

**Domain Computers: (Works fine with both Password and Hash)**

```bash
nxc smb mgmt.lab.local -u testuser -p PASSWORD -x hostname
SMB         192.168.1.31    445    MGMT          [*] Windows 10 / Server 2019 Build 17763 x64 (name:MGMT) (domain:lab.local) (signing:False) (SMBv1:False)
SMB         192.168.1.31    445    MGMT          [+] lab.local\testuser:PASSWORD (Pwn3d!)
SMB         192.168.1.31    445    MGMT          [+] Executed command via wmiexec
SMB         192.168.1.31    445    MGMT          Mgmt
```

**Domain Controller: (Says Pwn3d! but then errors out  with both Password and Hash)**

```bash
nxc smb dc.lab.local -u testuser -p PASSWORD
SMB         192.168.1.2     445    DC            [*] Windows 10 / Server 2019 Build 17763 x64 (name:DC) (domain:lab.local) (signing:True) (SMBv1:False)
SMB         192.168.1.2     445    DC            [+] lab.local\testuser:PASSWORD (Pwn3d!)
[23:41:00] ERROR    Exception while calling proto_flow() on target dc.lab.local: zip() argument 2 is longer than argument 1                     connection.py:176
                    ╭──────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────╮
                    │ in __init__:168                                                                                                                    │
                    │                                                                                                                                    │
                    │ in proto_flow:235                                                                                                                  │
                    │                                                                                                                                    │
                    │ in login:571                                                                                                                       │
                    │                                                                                                                                    │
                    │ in try_credentials:498                                                                                                             │
                    │                                                                                                                                    │
                    │ /tmp/_MEI1Zd1uI/nxc/protocols/smb.py:475 in plaintext_login                                                                        │
                    │                                                                                                                                    │
                    │    472 │   │   │   │   add_user_bh(self.username, self.domain, self.logger, self.config)                                           │
                    │    473 │   │   │   if self.admin_privs:                                                                                            │
                    │    474 │   │   │   │   self.logger.debug(f"Adding admin user:                                                                      │
                    │        {self.domain}/{self.username}:{self.password}@{self.host}")                                                                 │
                    │ ❱  475 │   │   │   │   self.db.add_admin_user("plaintext", domain, self.username,                                                  │
                    │        self.password, self.host, user_id=user_id)                                                                                  │
                    │    476 │   │   │   │   add_user_bh(f"{self.hostname}$", domain, self.logger, self.config)                                          │
                    │    477 │   │   │                                                                                                                   │
                    │    478 │   │   │   # check https://github.com/byt3bl33d3r/CrackMapExec/issues/321                                                  │
                    │                                                                                                                                    │
                    │ /tmp/_MEI1Zd1uI/nxc/protocols/smb/database.py:352 in add_admin_user                                                                │
                    │                                                                                                                                    │
                    │   349 │   │   hosts = self.get_hosts(host)                                                                                         │
                    │   350 │   │                                                                                                                        │
                    │   351 │   │   if users and hosts:                                                                                                  │
                    │ ❱ 352 │   │   │   for user, host in zip(users, hosts, strict=True):                                                                │
                    │   353 │   │   │   │   user_id = user[0]                                                                                            │
                    │   354 │   │   │   │   host_id = host[0]                                                                                            │
                    │   355 │   │   │   │   link = {"userid": user_id, "hostid": host_id}                                                                │
                    ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
                    ValueError: zip() argument 2 is longer than argument 1
```

**NetExec info**
 - OS: Kali
 - Version: 1.3.0  (Commit: f8293d15)
 - Manually compiled from the source on March 13th

**Comment by NeffIsBack** [comment]
Hi this has been fixed a few days ago: https://github.com/Pennyw0rth/NetExec/pull/590

Please update and retry

**Comment by w3soul** [comment]
Hi, 

Just compiled the binary from latest source code:

```bash
./nxc smb mgmt -u administrator -H 43b70d2d971805f419e02882997f83ff
  File "/tmp/_MEIsdvxfe/nxc/protocols/smb.py", line 16, in <module>
    from impacket.examples.regsecrets import (
ModuleNotFoundError: No module named 'impacket.examples.regsecrets'
[PYI-1704:ERROR] Failed to execute script 'netexec' due to unhandled exception!
```

```bash
which regsecrets.py 
/tmp/venv/bin/regsecrets.py
```

```bash
regsecrets.py -h
Impacket v0.13.0.dev0+20250326.105809.0711a41 - Copyright Fortra, LLC and its affiliated companies 

usage: regsecrets.py [-h] [-ts] [-debug] [-system SYSTEM] [-bootkey BOOTKEY] [-nosam] [-nocache] [-nolsa] [-throttle THROTTLE] [-outputfile OUTPUTFILE] [-history]
                     [-hashes LMHASH:NTHASH] [-no-pass] [-k] [-aesKey hex key] [-keytab KEYTAB] [-dc-ip ip address] [-target-ip ip address]
                     target

Performs various techniques to dump secrets from the remote machine without executing any agent there.
[...]
```

**Comment by NeffIsBack** [comment]
Ah yes the spec file wasn't updated since the last PRs. Please use pipx if you can.

Gonna fix the spec file tomorrow

**Comment by w3soul** [comment]
Hey, it works fine with pipx install.
Would greatly appreciate, if you could update the spec's file.
Manual compile always the best option :)

**Comment by NeffIsBack** [comment]
Should be fixed with #620

**Comment by w3soul** [comment]
Just recompiled. bit still have the same error, only for DC not for Domain joined machines:

```bash
 nxc                                                                                                                                                                           
    Version : 1.3.0                                                                                                                                                         
    Codename: NeedForSpeed                                                                                                                                                  
    Commit  : 2d3e1be1
```

Error:

```bash
[14:38:08] ERROR    Exception while calling proto_flow() on target us.lab.local: zip() argument 2 is longer than argument 1                     connection.py:176
                    ╭──────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────╮
                    │ in __init__:168                                                                                                                    │
                    │                                                                                                                                    │
                    │ in proto_flow:235                                                                                                                  │
                    │                                                                                                                                    │
                    │ in login:571                                                                                                                       │
                    │                                                                                                                                    │
                    │ in try_credentials:508                                                                                                             │
                    │                                                                                                                                    │
                    │ /tmp/_MEIIkQ6kM/nxc/protocols/smb.py:542 in hash_login                                                                             │
                    │                                                                                                                                    │
                    │    539 │   │   │   if not self.args.local_auth and self.username != "":                                                            │
                    │    540 │   │   │   │   add_user_bh(self.username, self.domain, self.logger, self.config)                                           │
                    │    541 │   │   │   if self.admin_privs:                                                                                            │
                    │ ❱  542 │   │   │   │   self.db.add_admin_user("hash", domain, self.username, nthash, self.host,                                    │
                    │        user_id=user_id)                                                                                                            │
                    │    543 │   │   │   │   add_user_bh(f"{self.hostname}$", domain, self.logger, self.config)                                          │
                    │    544 │   │   │                                                                                                                   │
                    │    545 │   │   │   # check https://github.com/byt3bl33d3r/CrackMapExec/issues/321                                                  │
                    │                                                                                                                                    │
                    │ /tmp/_MEIIkQ6kM/nxc/protocols/smb/database.py:353 in add_admin_user                                                                │
                    │                                                                                                                                    │
                    │   350 │   │                                                                                                                        │
                    │   351 │   │   if users and hosts:                                                                                                  │
                    │   352 │   │   │   nxc_logger.debug(f"users: {users}, hosts: {hosts}")                                                              │
                    │ ❱ 353 │   │   │   for user, host in zip(users, hosts, strict=True):                                                                │
                    │   354 │   │   │   │   user_id = user[0]                                                                                            │
                    │   355 │   │   │   │   host_id = host[0]                                                                                            │
                    │   356 │   │   │   │   link = {"userid": user_id, "hostid": host_id}                                                                │
                    ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
                    ValueError: zip() argument 2 is longer than argument 1

```

**Comment by NeffIsBack** [comment]
Hmm okay, please provide the debug log of that command

**Comment by 0xGreen** [comment]
> Don't Forget to trash the nxc folder

This works!! Just removed the .nxc folder and now working fine for both DC and others.

Thankyou @NeffIsBack @mpgn

**Comment by w3soul** [comment]
> Don't Forget to trash the nxc folder

This works!! Just removed the `.nxc`  and now all is good for both DC and others.

Thankyou @NeffIsBack @mpgn.
