### ISSUE TITLE
Compiled Versions Missing Required Module(s)

### ISSUE THREAD

**Issue by Kahvi-0** [Pennyw0rth/NetExec#91]
It appears that module(s) required for the LDAP protocol to run in the windows executable are not present. 

Command: `nxc.exe ldap 10.10.10.3`
Resulted in:
![1 (2)](https://github.com/Pennyw0rth/NetExec/assets/46513413/ede93d41-8788-4a51-819f-22efa3709d6c)

![2](https://github.com/Pennyw0rth/NetExec/assets/46513413/17a3aa1f-4aa3-4c86-8fae-6d0a7d347133)

**Expected behavior**
The netexec LDAP protocol to function without error.

**NetExec info**
 - OS: Windows 10, Kali
 - Version of nxc: 1.0.0
 - Installed from: Executable

**Comment by NeffIsBack** [comment]
Hi, thanks for the report. This should already be fixed with #79.
I rerun the build-binary action for you so try the new binary:

https://github.com/Pennyw0rth/NetExec/suites/16742192422/artifacts/1004814088

**Comment by Kahvi-0** [comment]
Unfortunately, I am still seeing the error.
 
![3](https://github.com/Pennyw0rth/NetExec/assets/46513413/38eff910-6c51-4f6b-9776-416725ab6ac3)

**Comment by NeffIsBack** [comment]
My bad, didn’t run the workflow properly. Can you try this one?

https://github.com/Pennyw0rth/NetExec/suites/17586142458/artifacts/1004886568

**Comment by Kahvi-0** [comment]
Looks all good on my end !!! Thanks !!
